field: 90552b17-3ba7-452a-9dfd-0b13004b4659 # Page - Block Content
fieldLayouts:
  af512a4a-3b2f-4137-b331-1deeb26fa3cd:
    tabs:
      -
        elements:
          -
            fieldUid: f64c5171-437f-45f4-ac5b-1164673e94f9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b21bc7f-953d-4003-a7d6-e27bea14f66e
            warning: null
            width: 100
          -
            fieldUid: feb39789-b26f-45a4-99fb-d7e4cc376989 # Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d178e82b-f190-4274-b459-af92f1f0339c
            warning: null
            width: 100
        name: Content
        uid: bde7f3d4-80a0-4bf2-8e74-9786f724493c
fields:
  f64c5171-437f-45f4-ac5b-1164673e94f9: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  feb39789-b26f-45a4-99fb-d7e4cc376989: # Padding
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: true
    settings:
      columnType: text
      dropdownOptions: '{% include ''_data/padding.json'' ignore missing %}'
    translationKeyFormat: null
    translationMethod: none
    type: lewisjenkins\craftdynamicfields\fields\Dropdown
handle: block
name: Block
sortOrder: 1
