fieldLayouts:
  f5656723-1457-4216-a988-c5d52d84dbdf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67f10ba1-ab2b-46d1-bf88-d66640d47849
            warning: null
            width: 100
          -
            fieldUid: 90552b17-3ba7-452a-9dfd-0b13004b4659 # Page - Block Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9614bf45-dfc8-4f1f-a637-a595191781aa
            warning: null
            width: 100
        name: General
        uid: 3c919082-eb32-41a6-a612-e4fab1b61438
      -
        elements:
          -
            fieldUid: d6471ab8-0d49-45bf-af5d-f0d2a860e267 # Meta & Social Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a249f9df-c224-499e-bd9b-53d007dc5955
            warning: null
            width: 100
        name: 'Meta & Social Data'
        uid: 6861ccae-0a7d-4656-88cf-99650154ff13
handle: pageBlock
hasTitleField: true
name: 'Page - Block'
section: a4cade2e-b351-4d0b-8087-3328bc132811 # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
