columnSuffix: null
contentColumnType: string
fieldGroup: a6548a8e-edd2-4cbb-9200-db7de2726f75 # Common
handle: siteHeaderNavigation
instructions: null
name: 'Site - Header Navigation'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 07997af2-2846-44ff-a240-009561640c19 # Links To
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_siteheadernavigation}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
