columnSuffix: null
contentColumnType: text
fieldGroup: a6548a8e-edd2-4cbb-9200-db7de2726f75 # Common
handle: siteCookieConsent
instructions: null
name: 'Site - Cookie Consent'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: 'Text Full.json'
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
